development:
  bucket: quorum-1
  access_key_id: AKIAI32U63YGQU33AZ6A
  secret_access_key: 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
test:
  bucket: quorum-1
  access_key_id: AKIAI32U63YGQU33AZ6A
  secret_access_key: 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
production:
  bucket: quorum-1
  access_key_id: AKIAI32U63YGQU33AZ6A
  secret_access_key: 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